// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQvalCKmcNpj8jYHQbTY7PnffAHGVyQz8',
    appId: '1:84996012588:web:b5520b449364c4cea42f89',
    messagingSenderId: '84996012588',
    projectId: 'todoapp-d3a76',
    authDomain: 'todoapp-d3a76.firebaseapp.com',
    storageBucket: 'todoapp-d3a76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4jZ7qkzLzGOYIdjVRXcn8jAxfO0GQjQ',
    appId: '1:84996012588:android:3d77b45223c6b0f5a42f89',
    messagingSenderId: '84996012588',
    projectId: 'todoapp-d3a76',
    storageBucket: 'todoapp-d3a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbu5MC4C7eJL14X54c2NN-4wMAexE9uYc',
    appId: '1:84996012588:ios:a56c2c22f59e58f3a42f89',
    messagingSenderId: '84996012588',
    projectId: 'todoapp-d3a76',
    storageBucket: 'todoapp-d3a76.appspot.com',
    iosClientId: '84996012588-gp0313msl4r9tfecmdgn571voudhl4ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbu5MC4C7eJL14X54c2NN-4wMAexE9uYc',
    appId: '1:84996012588:ios:a56c2c22f59e58f3a42f89',
    messagingSenderId: '84996012588',
    projectId: 'todoapp-d3a76',
    storageBucket: 'todoapp-d3a76.appspot.com',
    iosClientId: '84996012588-gp0313msl4r9tfecmdgn571voudhl4ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
